name: Release

on:
  push:
    tags:
      - 'v*'

env:
  GITHUB_TOKEN: ${{ secrets.BASE_TOKEN }}

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - run: npx changelogithub

      - name: Log in to the registry
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm login --registry=https://registry.npmjs.org/ --scope=@ilinfen --always-auth

      - name: Set NPM_TOKEN environment variable
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm install && npm publish
